# Ways to create tensors 



1.   tf.constant()
2.   tf.Variable()
3.   tf.random.Generator.from_seed()

And Shuffle a Tensor




In [22]:
import tensorflow as tf

print(tf.__version__)

2.12.0


### 1. tf.constant()

In [37]:
# creating a scalar

scalar = tf.constant(9)
scalar
#scalar.assign(8)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [24]:
#check dimension of scalar, it should be 0, cause scalar has 0 dimensions.
# for the same reason, Scalars are called Rank 0 Tensors

scalar.ndim

0

In [27]:
# creating a vector
# vectors are Rank 1 Tensors

vector = tf.constant([28,15,9])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([28, 15,  9], dtype=int32)>

In [28]:
vector.ndim

1

In [30]:
# creating a Matrix

matrix = tf.constant([[16,28,27],
                      [13,8,11],
                      [8,16,28]],dtype = float)
matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[16., 28., 27.],
       [13.,  8., 11.],
       [ 8., 16., 28.]], dtype=float32)>

In [31]:
matrix.ndim

2

In [32]:
# creating a 3D Tensor


tensor_3d = tf.constant([[[1,2,3],
                          [4,5,6]],
                         [[2,3,4],
                          [5,6,7]],
                         [[2,3,6],
                          [8,9,7]] ])
tensor_3d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 4],
        [5, 6, 7]],

       [[2, 3, 6],
        [8, 9, 7]]], dtype=int32)>

In [33]:
tensor_3d.ndim

3

### 2. tf.Variable()

When created a tensor using tf.constant(), we CANNOT modify the elements inside.
And so if we want to create a mutable tensor, then we can go for tf.Variable()

In [44]:
scalar1 = tf.Variable(9)
scalar1.assign(13)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=13>

In [45]:
scalar, scalar1

(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=13>)

In [46]:
vector1 = tf.Variable([9,15,28])
vector1

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 9, 15, 28], dtype=int32)>

In [47]:
# to change elements inside

vector1[2].assign(16)
vector1

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 9, 15, 16], dtype=int32)>

### 3. tf.random.Generator.from_seed()

In [48]:
random_matrix = tf.random.Generator.from_seed(45)
random_matrix = random_matrix.normal(shape=(4,5))
random_matrix

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ],
       [-0.4462975 , -2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ],
       [-0.6161736 , -1.9441465 , -0.48293006, -0.52447474, -1.0345329 ],
       [ 1.3066901 , -1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],
      dtype=float32)>

### 4. Shuffle a Tensor

In [50]:
shuffled_matrix = tf.random.shuffle(random_matrix)
shuffled_matrix

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[-0.4462975 , -2.3410842 ,  0.99009085, -0.0876323 , -0.635568  ],
       [ 1.3066901 , -1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ],
       [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ,  1.6874489 ],
       [-0.6161736 , -1.9441465 , -0.48293006, -0.52447474, -1.0345329 ]],
      dtype=float32)>