### Getting information from Tensors

Tensor Attributes



* shape
* ndim/rank
* size
* accessing elements inside a tensor


In [16]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.12.0


In [17]:
# create a 3D Tensor


tensor_3d = tf.zeros(shape=(2,3,5))
tensor_3d

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

### 1. Shape of Tensor

In [18]:
tensor_3d.shape

TensorShape([2, 3, 5])

### 2. Rank of Tensor

In [19]:
tensor_3d.ndim

3

### 3. Size of Tensor

In [20]:
tf.size(tensor_3d)


<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [21]:
tf.size(tensor_3d).numpy() #converting into numpy for easy interpretation of result/output


30

### 4. Accessing Elements inside a Tensor

In [22]:
tensor_3d[-1][1][3]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

### Making a pretty print statement with the above attributes

In [25]:

print("Data type of every elements: ",tensor_3d.dtype)
print("Number of Dimensions(Rank): ",tensor_3d.ndim)
print("Shape of the Tensor: ",tensor_3d.shape)
print("Elements along the 0 axis: ", tensor_3d.shape[0])
print("Elements along the last axis: ", tensor_3d.shape[-1])
print("Total no.of elements in the Tensor: ",tf.size(tensor_3d))
print("Total no.of elements in the Tensor: ",tf.size(tensor_3d).numpy())

Data type of every elements:  <dtype: 'float32'>
Number of Dimensions(Rank):  3
Shape of the Tensor:  (2, 3, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total no.of elements in the Tensor:  tf.Tensor(30, shape=(), dtype=int32)
Total no.of elements in the Tensor:  30
