### Indexing Tensors

In [1]:
import tensorflow as tf

In [7]:
tensor_3d = tf.random.Generator.from_seed(43)
tensor_3d = tensor_3d.uniform(shape=(2,3,4),minval=0,maxval=20,dtype=tf.int32)
tensor_3d

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 6,  1, 11,  7],
        [ 2,  7, 11,  6],
        [ 0, 13, 15,  2]],

       [[ 8, 13,  6,  7],
        [ 3,  9, 18,  9],
        [14,  9,  6, 17]]], dtype=int32)>

In [9]:
tensor_3d[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1), dtype=int32, numpy=array([[[6]]], dtype=int32)>

In [10]:
tensor_3d[-1,-1,-1]

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [16]:
tensor_3d[-1,1:,1:-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 18],
       [ 9,  6]], dtype=int32)>

In [18]:
tensor_3d[:1] # It includes only the first slice of the original tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[ 6,  1, 11,  7],
        [ 2,  7, 11,  6],
        [ 0, 13, 15,  2]]], dtype=int32)>

In [19]:
tensor_3d[:1,1:,2:] # [:] this means all rows and columns in a Tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11,  6],
        [15,  2]]], dtype=int32)>

In [22]:
tensor_3d[-1,:2,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 13],
       [ 3,  9]], dtype=int32)>

In [25]:
tensor_3d[:-1]

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[ 6,  1, 11,  7],
        [ 2,  7, 11,  6],
        [ 0, 13, 15,  2]]], dtype=int32)>

### tensor[...,newaxis] ---> To add an extra dimension to a Tensor

In [28]:
# adding an extra dimension to a Tensor

tensor_4d = tensor_3d[...,tf.newaxis]
tensor_4d

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[ 6],
         [ 1],
         [11],
         [ 7]],

        [[ 2],
         [ 7],
         [11],
         [ 6]],

        [[ 0],
         [13],
         [15],
         [ 2]]],


       [[[ 8],
         [13],
         [ 6],
         [ 7]],

        [[ 3],
         [ 9],
         [18],
         [ 9]],

        [[14],
         [ 9],
         [ 6],
         [17]]]], dtype=int32)>

In [32]:
tensor_4d[0,2,-1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

### Alternate to newaxis ---> tf.expand_dims(input, axis= D)

In [34]:
tensor_4d = tf.expand_dims(tensor_3d,axis =1)

In [35]:
tensor_4d

<tf.Tensor: shape=(2, 1, 3, 4), dtype=int32, numpy=
array([[[[ 6,  1, 11,  7],
         [ 2,  7, 11,  6],
         [ 0, 13, 15,  2]]],


       [[[ 8, 13,  6,  7],
         [ 3,  9, 18,  9],
         [14,  9,  6, 17]]]], dtype=int32)>