In [36]:
import tensorflow as tf

### Basic Arithmetic Operations on Tensors





In [40]:
# create a random 3D tensor

tensor_3d = tf.random.Generator.from_seed(45)
tensor_3d = tensor_3d.uniform(shape=(2,4,5),dtype=tf.int32,minval=1,maxval=30)
tensor_3d

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[16, 16, 23,  9, 25],
        [23, 20, 13, 12, 12],
        [23, 15, 12, 10, 13],
        [22, 24,  5,  7, 10]],

       [[19,  1, 28,  3,  3],
        [ 8, 29,  6, 21, 26],
        [22, 11, 11, 21,  5],
        [ 8,  8, 11,  7,  8]]], dtype=int32)>

**Quick Note:** Basic Operations performed on a Tensor didn't have inplace = true effect. If you wanna save the changes, you might have to assign the result to a variable.

In [44]:
# Adding numbers to a Tensor

tensor_3d + 1

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[17, 17, 24, 10, 26],
        [24, 21, 14, 13, 13],
        [24, 16, 13, 11, 14],
        [23, 25,  6,  8, 11]],

       [[20,  2, 29,  4,  4],
        [ 9, 30,  7, 22, 27],
        [23, 12, 12, 22,  6],
        [ 9,  9, 12,  8,  9]]], dtype=int32)>

In [46]:
# Subtracting numbers from a Tensor

tensor_3d - 1

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[15, 15, 22,  8, 24],
        [22, 19, 12, 11, 11],
        [22, 14, 11,  9, 12],
        [21, 23,  4,  6,  9]],

       [[18,  0, 27,  2,  2],
        [ 7, 28,  5, 20, 25],
        [21, 10, 10, 20,  4],
        [ 7,  7, 10,  6,  7]]], dtype=int32)>

In [47]:
# Multiplying numbers to a Tensor

tensor_3d * 0

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int32)>

In [48]:
# Dividing numbers from a Tensor

tensor_3d / 2

<tf.Tensor: shape=(2, 4, 5), dtype=float64, numpy=
array([[[ 8. ,  8. , 11.5,  4.5, 12.5],
        [11.5, 10. ,  6.5,  6. ,  6. ],
        [11.5,  7.5,  6. ,  5. ,  6.5],
        [11. , 12. ,  2.5,  3.5,  5. ]],

       [[ 9.5,  0.5, 14. ,  1.5,  1.5],
        [ 4. , 14.5,  3. , 10.5, 13. ],
        [11. ,  5.5,  5.5, 10.5,  2.5],
        [ 4. ,  4. ,  5.5,  3.5,  4. ]]])>

### tf.math functions

In [50]:
# Multiplying numbers to a Tensor using tf.math.multiply()

tf.math.multiply(tensor_3d, 2)

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[32, 32, 46, 18, 50],
        [46, 40, 26, 24, 24],
        [46, 30, 24, 20, 26],
        [44, 48, 10, 14, 20]],

       [[38,  2, 56,  6,  6],
        [16, 58, 12, 42, 52],
        [44, 22, 22, 42, 10],
        [16, 16, 22, 14, 16]]], dtype=int32)>

In [51]:
# Adding numbers to a Tensor using tf.math.add()

tf.math.add(tensor_3d, 2)

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[18, 18, 25, 11, 27],
        [25, 22, 15, 14, 14],
        [25, 17, 14, 12, 15],
        [24, 26,  7,  9, 12]],

       [[21,  3, 30,  5,  5],
        [10, 31,  8, 23, 28],
        [24, 13, 13, 23,  7],
        [10, 10, 13,  9, 10]]], dtype=int32)>

In [52]:
# Subtracting numbers from a Tensor using tf.math.subtract()

tf.math.subtract(tensor_3d, 2)

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[14, 14, 21,  7, 23],
        [21, 18, 11, 10, 10],
        [21, 13, 10,  8, 11],
        [20, 22,  3,  5,  8]],

       [[17, -1, 26,  1,  1],
        [ 6, 27,  4, 19, 24],
        [20,  9,  9, 19,  3],
        [ 6,  6,  9,  5,  6]]], dtype=int32)>

In [53]:
# Dividing numbers from a Tensor using tf.math.divide()

tf.math.divide(tensor_3d, 2)

<tf.Tensor: shape=(2, 4, 5), dtype=float64, numpy=
array([[[ 8. ,  8. , 11.5,  4.5, 12.5],
        [11.5, 10. ,  6.5,  6. ,  6. ],
        [11.5,  7.5,  6. ,  5. ,  6.5],
        [11. , 12. ,  2.5,  3.5,  5. ]],

       [[ 9.5,  0.5, 14. ,  1.5,  1.5],
        [ 4. , 14.5,  3. , 10.5, 13. ],
        [11. ,  5.5,  5.5, 10.5,  2.5],
        [ 4. ,  4. ,  5.5,  3.5,  4. ]]])>

### Advanced tf.math functions

In [55]:
# tf.math.pow: Computes the element-wise power of a tensor.

tf.math.pow(tensor_3d,2)

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[256, 256, 529,  81, 625],
        [529, 400, 169, 144, 144],
        [529, 225, 144, 100, 169],
        [484, 576,  25,  49, 100]],

       [[361,   1, 784,   9,   9],
        [ 64, 841,  36, 441, 676],
        [484, 121, 121, 441,  25],
        [ 64,  64, 121,  49,  64]]], dtype=int32)>

In [59]:
# tf.math.reduce_mean: Computes the mean of all elements in a tensor.


print(tf.math.reduce_mean(tensor_3d))
print(tf.math.reduce_mean(tensor_3d).numpy())

tf.Tensor(14, shape=(), dtype=int32)
14
