### Rules of Matrix Multiplication


1.   The inner dimensions of the two matrices have to be the same.
2.   The resulting matrix of the multiplication is having the outer dimensions of those two matrices as its shape.



In [63]:
import tensorflow as tf

### 1. Matrix Multiplication by reshaping

tf.reshape(tensor, shape=(x,y)

In [69]:
# Try matrix multiplication with matmul()

tensor_1 = tf.random.Generator.from_seed(12)
tensor_1 = tensor_1.uniform(shape=(2,3),dtype = tf.int32,minval = 1, maxval = 10)
tensor_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[8, 5, 4],
       [8, 5, 4]], dtype=int32)>

In [70]:
tensor_2 = tf.random.Generator.from_seed(15)
tensor_2 = tensor_2.uniform(shape=(3,4),dtype = tf.int32,minval = 1, maxval = 10)
tensor_2

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[9, 8, 2, 6],
       [6, 5, 8, 5],
       [6, 2, 7, 9]], dtype=int32)>

In [72]:
matrix_mult = tf.matmul(tensor_1,tensor_2)
matrix_mult

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[126,  97,  84, 109],
       [126,  97,  84, 109]], dtype=int32)>

In [73]:
tensor_3 = tf.random.Generator.from_seed(12)
tensor_3 = tensor_3.uniform(shape=(3,4),dtype = tf.int32,minval = 1, maxval = 10)
tensor_3

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[8, 5, 4, 8],
       [5, 4, 9, 9],
       [6, 3, 8, 1]], dtype=int32)>

In [76]:
tensor_4 = tf.random.Generator.from_seed(25)
tensor_4 = tensor_4.uniform(shape=(3,4),dtype = tf.int32,minval = 1, maxval = 10)
tensor_4

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[9, 7, 8, 6],
       [6, 3, 7, 8],
       [2, 2, 8, 1]], dtype=int32)>

In [78]:
#matrix_multiplication2 = tf.matmul(tensor_3,tensor_4)
# Rule 1 isn't true here, inner dimensions aren't equal.

In [89]:
reshaped_tensor_4 = tf.reshape(tensor_4, shape=(4,3)) #reshaping tensor

In [90]:
tensor_3.shape,reshaped_tensor_4.shape # checking if inner dimensions of two tensors are same

(TensorShape([3, 4]), TensorShape([4, 3]))

In [87]:
matrix_multiplication2 = tf.matmul(tensor_3,reshaped_tensor_4)

In [88]:
matrix_multiplication2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[146, 182,  95],
       [150, 203,  79],
       [130, 132,  74]], dtype=int32)>

### 2. Matrix Multiplication by Transposing

tf.transpose(tensor)


In [91]:
tensor_5 = tf.random.Generator.from_seed(25)
tensor_5 = tensor_5.uniform(shape=(3,4),dtype = tf.int32,minval = 1, maxval = 10)
tensor_5

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[9, 7, 8, 6],
       [6, 3, 7, 8],
       [2, 2, 8, 1]], dtype=int32)>

In [92]:
tensor_6 = tf.random.Generator.from_seed(28)
tensor_6 = tensor_6.uniform(shape=(3,4),dtype = tf.int32,minval = 1, maxval = 10)
tensor_6

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[4, 8, 5, 5],
       [5, 6, 4, 7],
       [7, 3, 8, 2]], dtype=int32)>

In [93]:
# Inner Dimensions of tensor_5 and tensor_6 aren't equal

tensor_5.shape, tensor_6.shape

(TensorShape([3, 4]), TensorShape([3, 4]))

In [94]:
# so, we can transpose tensor_6 into a 4x3 matrix there by making inner dimensions of two matrices match

transposed_tensor_6 = tf.transpose(tensor_6)
transposed_tensor_6

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[4, 5, 7],
       [8, 6, 3],
       [5, 4, 8],
       [5, 7, 2]], dtype=int32)>

In [95]:
# now check for matching inner dimensions of two tensors

tensor_5.shape, transposed_tensor_6.shape

(TensorShape([3, 4]), TensorShape([4, 3]))

In [96]:
# now we can proceed with Matrix Multiplication

tensor_multiplication = tf.matmul(tensor_5,transposed_tensor_6)
tensor_multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[162, 161, 160],
       [123, 132, 123],
       [ 69,  61,  86]], dtype=int32)>

### The Dot Product

Matrix Multiplication is also referred to as the dot prouct

You can perform matrix multiplication using:
* tf.matmul()
* tf.tensordot()
* @

In [97]:
tensor_5, tensor_6

(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[9, 7, 8, 6],
        [6, 3, 7, 8],
        [2, 2, 8, 1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[4, 8, 5, 5],
        [5, 6, 4, 7],
        [7, 3, 8, 2]], dtype=int32)>)

In [99]:
tensor_5.shape, tensor_6.shape

(TensorShape([3, 4]), TensorShape([3, 4]))

In [98]:
# perform matrix multiplication between 5 and 6(transposed)

tf.matmul(tf.transpose(tensor_5),tensor_6)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 80, 114,  85,  91],
       [ 57,  80,  63,  60],
       [123, 130, 132, 105],
       [ 71,  99,  70,  88]], dtype=int32)>

In [101]:
# perform matrix multiplication between 5 and 6(reshaped)
tf.matmul(tf.reshape(tensor_5, shape=(4,3)),tensor_6)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[127, 138, 137, 110],
       [ 75,  93,  78,  78],
       [ 82, 110,  83,  95],
       [ 55,  67,  50,  68]], dtype=int32)>