## Changing the default data type of a Tensor(32 to 16 bit precision)

tf.cast(tensor, dtype = tf.float32/int32/float16/int16)

In [107]:
# Create a tensor with default data type(int)

A = tf.constant([1,7,4])
A


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 7, 4], dtype=int32)>

In [108]:
# Create a tensor with default data type(int)

B = tf.constant([1.,7.,4.])
B


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 7., 4.], dtype=float32)>

In [109]:
# Change from int32 to int16 (reduced precision)

C = tf.cast(A, dtype = tf.int16)
C

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 7, 4], dtype=int16)>

In [110]:
# Change from float32 to float16 (reduced precision)

D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 7., 4.], dtype=float16)>

In [111]:
# Change from int32 to float32

E = tf.cast(A, dtype = tf.float32)
E

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 7., 4.], dtype=float32)>